<?php

class TeamsResponseTest extends TestCase
{

    protected $response;

    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $contents = json_encode(file(app_path().'/../tests/Yahoo/Responses/response.json', true));

        $stream = Mockery::mock(\GuzzleHttp\Psr7\Stream::class)
            ->shouldReceive('getContents')
            ->andReturn($contents);

        $stream->shouldReceive('close');

        $responseIntercace = Mockery::mock(\Psr\Http\Message\ResponseInterface::class);
        $responseIntercace
            ->shouldReceive('getBody')
            ->andReturn($stream->getMock())
            ->mock();

        $this->service = new \App\Yahoo\Responses\User\TeamResponse($responseIntercace);

    }

    public function testSimpleJson()
    {
        $data = $this->service->simpleResponse();
        $this->assertTrue(true);
    }
}

