<?php

namespace App\Yahoo\Services\Fantasy\Leagues;

use App\Contracts\Yahoo\ResponseInterface;
use App\Contracts\Yahoo\Services\Leagues\GetLeaguesContract;
use App\Game;
use App\Yahoo\YahooService;

class Get extends YahooService implements GetLeaguesContract
{
    public $uriParams = ['league_key' => null];
    protected $uri = 'https://fantasysports.yahooapis.com/fantasy/v2/leagues;league_keys={league_key}';

    public function __construct(ResponseInterface $response = null)
    {
        parent::__construct();
        $this->responseClass = $response;
    }

    public function setUriParams(string $key, string $value)
    {
        $this->uriParams[$key] = $value;

    }

    public function call()
    {
        return parent::call(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Game $game
     * @param string $league_id
     * @return string
     */
    public static function getLeagueKey(Game $game, string $league_id)
    {
        return $game->game_id .'.l.'.$league_id;
    }
}