<?php

namespace App\Yahoo\Services\Fantasy\Leagues;

use App\Contracts\Yahoo\ResponseInterface;
use App\Contracts\Yahoo\Services\Leagues\GetLeaguesContract;
use App\Yahoo\YahooService;

class GetSettings extends YahooService implements GetLeaguesContract
{
    public $uriParams = [
        'league_key' => null,
        'game_key' => null
    ];

    protected $uri = 'https://fantasysports.yahooapis.com/fantasy/v2/league/{game_key}.l.{league_key}/settings';

    public function __construct(ResponseInterface $response)
    {
        parent::__construct();

        $this->responseClass = $response;
    }


    public function setUriParams(string $key, string $value)
    {
        $this->uriParams[$key] = $value;
    }

    public function call()
    {
        $this->build();
        $this->tries = $this->tries++;
        $this->response = $this->client->request($this->method, $this->returnUrlWithParams(), $this->options);
        $call =  parent::call(); // TODO: Change the autogenerated stub
        dump($call->simpleResponse());exit;
        return $this->handleResponse();
    }
}